import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Clear existing seed data
  await prisma.event.deleteMany({ where: { source: "seed" } });

  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  function addDays(date: Date, days: number): Date {
    const d = new Date(date);
    d.setDate(d.getDate() + days);
    return d;
  }

  function setTime(date: Date, hours: number, minutes: number = 0): Date {
    const d = new Date(date);
    d.setHours(hours, minutes, 0, 0);
    return d;
  }

  const events = [
    {
      sourceId: "seed-1",
      source: "seed",
      title: "Toddler Storytime at the Library",
      description:
        "Join us for a fun-filled storytime for toddlers and their caregivers. Includes songs, finger plays, and a simple craft.",
      startDate: setTime(addDays(today, 1), 10, 0),
      endDate: setTime(addDays(today, 1), 11, 0),
      venueName: "Monroe County Public Library",
      address: "303 E Kirkwood Ave",
      city: "Bloomington",
      state: "IN",
      zipCode: "47408",
      latitude: 39.1653,
      longitude: -86.5264,
      ageGroups: JSON.stringify(["baby", "toddler"]),
      sourceUrl: "https://example.com/storytime",
      isFree: true,
    },
    {
      sourceId: "seed-2",
      source: "seed",
      title: "Family Nature Walk at Bryan Park",
      description:
        "Explore nature trails with a guided walk suitable for all ages. Learn about local plants and wildlife.",
      startDate: setTime(addDays(today, 1), 9, 0),
      endDate: setTime(addDays(today, 1), 10, 30),
      venueName: "Bryan Park",
      address: "1150 S Henderson St",
      city: "Bloomington",
      state: "IN",
      zipCode: "47401",
      latitude: 39.1553,
      longitude: -86.5364,
      ageGroups: JSON.stringify(["family"]),
      sourceUrl: "https://example.com/nature-walk",
      isFree: true,
    },
    {
      sourceId: "seed-3",
      source: "seed",
      title: "Kids Art Workshop: Painting Fun",
      description:
        "A hands-on art workshop for children ages 5-12. All materials provided.",
      startDate: setTime(addDays(today, 2), 14, 0),
      endDate: setTime(addDays(today, 2), 16, 0),
      venueName: "Bloomington Arts Center",
      address: "205 E 4th St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1663,
      longitude: -86.5274,
      ageGroups: JSON.stringify(["kid"]),
      sourceUrl: "https://example.com/art-workshop",
      isFree: false,
    },
    {
      sourceId: "seed-4",
      source: "seed",
      title: "Teen Game Night",
      description:
        "Board games, video games, and pizza for teens ages 13-17. Free and fun!",
      startDate: setTime(addDays(today, 2), 18, 0),
      endDate: setTime(addDays(today, 2), 20, 0),
      venueName: "Youth Center",
      address: "100 W 7th St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1673,
      longitude: -86.5254,
      ageGroups: JSON.stringify(["teen"]),
      sourceUrl: "https://example.com/game-night",
      isFree: true,
    },
    {
      sourceId: "seed-5",
      source: "seed",
      title: "Craft Beer Festival",
      description:
        "Sample craft beers from 20+ local and regional breweries. Must be 21+.",
      startDate: setTime(addDays(today, 3), 16, 0),
      endDate: setTime(addDays(today, 3), 21, 0),
      venueName: "Convention Center",
      address: "302 S College Ave",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1643,
      longitude: -86.5284,
      ageGroups: JSON.stringify(["adult"]),
      sourceUrl: "https://example.com/beer-fest",
      isFree: false,
    },
    {
      sourceId: "seed-6",
      source: "seed",
      title: "Baby Music & Movement",
      description:
        "A gentle music class for babies and their parents. Instruments, songs, and movement activities.",
      startDate: setTime(addDays(today, 1), 13, 0),
      endDate: setTime(addDays(today, 1), 13, 45),
      venueName: "Community Center",
      address: "401 N Morton St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1713,
      longitude: -86.5334,
      ageGroups: JSON.stringify(["baby", "toddler"]),
      sourceUrl: "https://example.com/baby-music",
      isFree: false,
    },
    {
      sourceId: "seed-7",
      source: "seed",
      title: "Saturday Farmers Market",
      description:
        "Fresh local produce, baked goods, crafts, and live music. Fun for the whole family!",
      startDate: setTime(addDays(today, 4), 8, 0),
      endDate: setTime(addDays(today, 4), 12, 0),
      venueName: "Showers Common",
      address: "401 N Morton St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1713,
      longitude: -86.5334,
      ageGroups: JSON.stringify(["family"]),
      sourceUrl: "https://example.com/farmers-market",
      isFree: true,
    },
    {
      sourceId: "seed-8",
      source: "seed",
      title: "Preschool Science Explorers",
      description:
        "Hands-on science experiments designed for ages 3-5. Explore water, magnets, and colors!",
      startDate: setTime(addDays(today, 3), 10, 30),
      endDate: setTime(addDays(today, 3), 11, 30),
      venueName: "WonderLab Museum",
      address: "308 W 4th St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1668,
      longitude: -86.5328,
      ageGroups: JSON.stringify(["preschool", "toddler"]),
      sourceUrl: "https://example.com/science-explorers",
      isFree: false,
    },
    {
      sourceId: "seed-9",
      source: "seed",
      title: "Lunchtime Yoga in the Park",
      description:
        "Free yoga class for adults. Bring your own mat. All levels welcome.",
      startDate: setTime(addDays(today, 1), 12, 0),
      endDate: setTime(addDays(today, 1), 13, 0),
      venueName: "Peoples Park",
      address: "514 E Kirkwood Ave",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1658,
      longitude: -86.5224,
      ageGroups: JSON.stringify(["adult"]),
      sourceUrl: "https://example.com/yoga",
      isFree: true,
    },
    {
      sourceId: "seed-10",
      source: "seed",
      title: "Family Movie Night: Outdoor Screening",
      description:
        "Bring blankets and enjoy a family-friendly movie under the stars.",
      startDate: setTime(addDays(today, 5), 20, 0),
      endDate: setTime(addDays(today, 5), 22, 0),
      venueName: "Switchyard Park",
      address: "801 S Rogers St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1583,
      longitude: -86.5374,
      ageGroups: JSON.stringify(["family"]),
      sourceUrl: "https://example.com/movie-night",
      isFree: true,
    },
    {
      sourceId: "seed-11",
      source: "seed",
      title: "Little Splashers Swim Class",
      description:
        "Introduction to water for toddlers ages 1-3 with a parent in the pool.",
      startDate: setTime(addDays(today, 2), 9, 30),
      endDate: setTime(addDays(today, 2), 10, 15),
      venueName: "Twin Lakes Recreation Center",
      address: "1700 W Bloomfield Rd",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1493,
      longitude: -86.5534,
      ageGroups: JSON.stringify(["baby", "toddler"]),
      sourceUrl: "https://example.com/swim-class",
      isFree: false,
    },
    {
      sourceId: "seed-12",
      source: "seed",
      title: "High School Battle of the Bands",
      description:
        "Local high school bands compete for the top spot. Teens and families welcome!",
      startDate: setTime(addDays(today, 6), 17, 0),
      endDate: setTime(addDays(today, 6), 20, 0),
      venueName: "Buskirk-Chumley Theater",
      address: "114 E Kirkwood Ave",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1658,
      longitude: -86.5309,
      ageGroups: JSON.stringify(["teen", "family"]),
      sourceUrl: "https://example.com/battle-bands",
      isFree: false,
    },
    {
      sourceId: "seed-13",
      source: "seed",
      title: "Toddler Tumble Time",
      description:
        "Open gym time for toddlers to climb, tumble, and play. Ages 1-4.",
      startDate: setTime(addDays(today, 3), 15, 0),
      endDate: setTime(addDays(today, 3), 16, 30),
      venueName: "Gymnastics Academy",
      address: "500 N Walnut St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1723,
      longitude: -86.5294,
      ageGroups: JSON.stringify(["toddler", "preschool"]),
      sourceUrl: "https://example.com/tumble-time",
      isFree: false,
    },
    {
      sourceId: "seed-14",
      source: "seed",
      title: "Wine Tasting Evening",
      description:
        "Explore wines from around the world with our expert sommelier. 21+ only.",
      startDate: setTime(addDays(today, 4), 19, 0),
      endDate: setTime(addDays(today, 4), 21, 0),
      venueName: "The Cellar Door",
      address: "200 S College Ave",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1648,
      longitude: -86.5284,
      ageGroups: JSON.stringify(["adult"]),
      sourceUrl: "https://example.com/wine-tasting",
      isFree: false,
    },
    {
      sourceId: "seed-15",
      source: "seed",
      title: "Playground Playdate: Cascade Park",
      description:
        "Meet other families at the playground! Bring snacks to share. All ages welcome.",
      startDate: setTime(addDays(today, 2), 10, 0),
      endDate: setTime(addDays(today, 2), 12, 0),
      venueName: "Cascade Park",
      address: "800 W Allen St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1703,
      longitude: -86.5424,
      ageGroups: JSON.stringify(["baby", "toddler", "preschool", "kid", "family"]),
      sourceUrl: "https://example.com/playdate",
      isFree: true,
    },
    {
      sourceId: "seed-16",
      source: "seed",
      title: "Middle School Robotics Club Open House",
      description:
        "See what the robotics club has been building! Great for teens interested in STEM.",
      startDate: setTime(addDays(today, 5), 15, 30),
      endDate: setTime(addDays(today, 5), 17, 0),
      venueName: "Tri-North Middle School",
      address: "1000 N Smith Rd",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1783,
      longitude: -86.5154,
      ageGroups: JSON.stringify(["teen", "kid"]),
      sourceUrl: "https://example.com/robotics",
      isFree: true,
    },
    {
      sourceId: "seed-17",
      source: "seed",
      title: "Baby Sensory Play",
      description:
        "Explore textures, lights, and sounds in a safe sensory play environment for babies 0-18 months.",
      startDate: setTime(addDays(today, 4), 10, 0),
      endDate: setTime(addDays(today, 4), 11, 0),
      venueName: "Little Sprouts Studio",
      address: "125 S College Ave",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1653,
      longitude: -86.5284,
      ageGroups: JSON.stringify(["baby"]),
      sourceUrl: "https://example.com/sensory-play",
      isFree: false,
    },
    {
      sourceId: "seed-18",
      source: "seed",
      title: "Community Dance: All Ages Welcome",
      description:
        "Live band, dancing, and refreshments. Everyone is invited to this free community event!",
      startDate: setTime(addDays(today, 6), 14, 0),
      endDate: setTime(addDays(today, 6), 17, 0),
      venueName: "City Hall Lawn",
      address: "401 N Morton St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1713,
      longitude: -86.5334,
      ageGroups: JSON.stringify(["family"]),
      sourceUrl: "https://example.com/community-dance",
      isFree: true,
    },
    {
      sourceId: "seed-19",
      source: "seed",
      title: "Nap-Friendly Afternoon: Toddler Art",
      description:
        "Art activities for toddlers scheduled after nap time! Ages 1-3. Paint, clay, and collage.",
      startDate: setTime(addDays(today, 3), 15, 30),
      endDate: setTime(addDays(today, 3), 16, 30),
      venueName: "Bloomington Arts Center",
      address: "205 E 4th St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1663,
      longitude: -86.5274,
      ageGroups: JSON.stringify(["toddler"]),
      sourceUrl: "https://example.com/toddler-art",
      isFree: false,
    },
    {
      sourceId: "seed-20",
      source: "seed",
      title: "Kids Soccer Clinic",
      description:
        "Free soccer skills clinic for children ages 5-12. Bring water and cleats.",
      startDate: setTime(addDays(today, 5), 9, 0),
      endDate: setTime(addDays(today, 5), 11, 0),
      venueName: "Winslow Sports Complex",
      address: "1500 W Adams St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1593,
      longitude: -86.5494,
      ageGroups: JSON.stringify(["kid"]),
      sourceUrl: "https://example.com/soccer-clinic",
      isFree: true,
    },
    {
      sourceId: "seed-21",
      source: "seed",
      title: "Evening Jazz at the Bluebird",
      description:
        "Live jazz performance. 21+ venue with full bar and appetizers.",
      startDate: setTime(addDays(today, 4), 20, 0),
      endDate: setTime(addDays(today, 4), 23, 0),
      venueName: "The Bluebird",
      address: "216 N Walnut St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1683,
      longitude: -86.5294,
      ageGroups: JSON.stringify(["adult"]),
      sourceUrl: "https://example.com/jazz-night",
      isFree: false,
    },
    {
      sourceId: "seed-22",
      source: "seed",
      title: "Morning Storytime at Barnes & Noble",
      description:
        "Storytime for preschoolers with activities and a free cookie!",
      startDate: setTime(addDays(today, 1), 10, 30),
      endDate: setTime(addDays(today, 1), 11, 15),
      venueName: "Barnes & Noble",
      address: "2813 E 3rd St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1618,
      longitude: -86.4984,
      ageGroups: JSON.stringify(["toddler", "preschool"]),
      sourceUrl: "https://example.com/bn-storytime",
      isFree: true,
    },
    {
      sourceId: "seed-23",
      source: "seed",
      title: "Family Bike Ride on the B-Line Trail",
      description:
        "A casual 3-mile family bike ride along the B-Line Trail. Helmets required.",
      startDate: setTime(addDays(today, 6), 9, 0),
      endDate: setTime(addDays(today, 6), 10, 30),
      venueName: "B-Line Trail - North Entrance",
      address: "N Morton St & W 7th St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1733,
      longitude: -86.5334,
      ageGroups: JSON.stringify(["kid", "family"]),
      sourceUrl: "https://example.com/bike-ride",
      isFree: true,
    },
    {
      sourceId: "seed-24",
      source: "seed",
      title: "Lunch Bunch: Toddler Social",
      description:
        "Bring your lunch and let the toddlers play! Structured activities from 12:30-1:30.",
      startDate: setTime(addDays(today, 2), 12, 30),
      endDate: setTime(addDays(today, 2), 13, 30),
      venueName: "Community Center",
      address: "401 N Morton St",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1713,
      longitude: -86.5334,
      ageGroups: JSON.stringify(["toddler"]),
      sourceUrl: "https://example.com/lunch-bunch",
      isFree: true,
    },
    {
      sourceId: "seed-25",
      source: "seed",
      title: "Teen Volunteer Day: Park Cleanup",
      description:
        "Earn volunteer hours while helping clean up local parks. Ages 13-17.",
      startDate: setTime(addDays(today, 7), 8, 0),
      endDate: setTime(addDays(today, 7), 12, 0),
      venueName: "Lower Cascades Park",
      address: "3000 Old State Rd 37 S",
      city: "Bloomington",
      state: "IN",
      latitude: 39.1423,
      longitude: -86.5134,
      ageGroups: JSON.stringify(["teen"]),
      sourceUrl: "https://example.com/volunteer-day",
      isFree: true,
    },
  ];

  for (const event of events) {
    await prisma.event.upsert({
      where: {
        source_sourceId: { source: event.source, sourceId: event.sourceId },
      },
      update: event,
      create: event,
    });
  }

  console.log(`Seeded ${events.length} events`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
